const express = require('express');
const router = express.Router();
const { Firestore } = require('@google-cloud/firestore');

// Initialize Firestore
const firestore = new Firestore();

// Swagger Documentation for Client APIs

/**
 * @swagger
 * components:
 *   schemas:
 *     Client:
 *       type: object
 *       properties:
 *         id:
 *           type: string
 *           description: The autogenerated ID of the client
 *         name:
 *           type: string
 *           description: The name of the client
 *         email:
 *           type: string
 *           description: The email of the client
 *         phone:
 *           type: string
 *           description: The phone number of the client
 *         fromAddress:
 *           type: string
 *           description: The address from where the client is moving
 *         toAddress:
 *           type: string
 *           description: The destination address of the move
 *         movingDate:
 *           type: string
 *           format: date-time
 *           description: The moving date
 */

/**
 * @swagger
 * /api/client:
 *   post:
 *     summary: Create a new client
 *     tags: [Client]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Client'
 *     responses:
 *       201:
 *         description: The client was successfully created
 *       500:
 *         description: Some server error
 */
router.post('/', async (req, res) => {
  try {
    const { name, email, phone, fromAddress, toAddress, movingDate } = req.body;
    
    const clientDocRef = await firestore.collection('Mes4DB').add({
      name: name || '',
      email: email || '',
      phone: phone || '',
      fromAddress: fromAddress || '',
      toAddress: toAddress || '',
      movingDate: movingDate || '',
    });

    res.status(201).json({ id: clientDocRef.id });
  } catch (error) {
    console.error('Error creating client:', error);
    res.status(500).json({ error: 'Failed to create client' });
  }
});

/**
 * @swagger
 * /api/client/{id}:
 *   get:
 *     summary: Get a client by ID
 *     tags: [Client]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: The client ID
 *     responses:
 *       200:
 *         description: The client data
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Client'
 *       404:
 *         description: Client not found
 *       500:
 *         description: Some server error
 */
router.get('/:id', async (req, res) => {
  try {
    const clientDoc = await firestore.collection('Mes4DB').doc(req.params.id).get();
    
    if (!clientDoc.exists) {
      return res.status(404).json({ error: 'Client not found' });
    }

    res.status(200).json(clientDoc.data());
  } catch (error) {
    res.status(500).json({ error: 'Failed to retrieve client' });
  }
});

module.exports = router;
